Issue1546 formatting for xml and sql
factcast/factcast pull request #1548
Opened 2021-08-25 23:30 UTC by uweschaefer

2021-08-30 13:24 UTC, BernhardBln requested changes

2021-08-30 13:24 UTC, BernhardBln commented on factcast-store/src/test/resources/test_schema.sql
> +  OR REPLACE FUNCTION notifyFactInsert() RETURNS TRIGGER AS $$ BEGIN PERFORM pg_notify(
Still wondering what the # sign does here. Comments in SQL would be "--"...

Apply formatter again after fixing this and check what happens...

```suggestion
CREATE OR REPLACE FUNCTION notifyFactInsert() RETURNS TRIGGER AS $$ BEGIN PERFORM pg_notify(
```

2021-08-30 13:24 UTC, BernhardBln commented on factcast-store/src/test/resources/test_schema.sql
> +# CREATE
```suggestion
CREATE
```

2021-08-30 13:24 UTC, BernhardBln commented on factcast-store/src/test/resources/test_schema.sql
> +  CONSTRAINT TRIGGER tr_deferred_fact_insert AFTER INSERT
Same

```suggestion
CREATE CONSTRAINT TRIGGER tr_deferred_fact_insert AFTER INSERT
```

2021-08-30 13:24 UTC, BernhardBln commented on factcast-store/src/test/resources/test_schema.sql
> +  SEQUENCE catchup_seq;
```suggestion
CREATE SEQUENCE catchup_seq;
```

2021-08-30 13:24 UTC, BernhardBln commented on factcast-store/src/test/resources/test_schema.sql
> +  TABLE
```suggestion
CREATE TABLE
```

2021-09-02 14:08 UTC, uweschaefer commented on pom.xml
> +								<include>**/*.xsd</include>
if anyone again formats .md files, i'll be on a killing spree... 
they are constantly broken due to 'clever' formatters not understanding forntmatter, mermaid or even simple markdown tables.

2021-09-02 14:08 UTC, uweschaefer commented on pom.xml
> +								<include>**/*.xsd</include>
what is there to format regarding property files?

2021-09-02 14:24 UTC, uweschaefer commented on pom.xml
> +								<include>**/*.xsd</include>
It is official: "formatting" property files this way is not a great idea either:

```
diff --git a/factcast-examples/factcast-example-tls-server/src/main/resources/application.properties b/factcast-examples/factcast-example-tls-server/src/main/resources/application.properties
index dcdd955b5..50f0ae150 100644
--- a/factcast-examples/factcast-example-tls-server/src/main/resources/application.properties
+++ b/factcast-examples/factcast-example-tls-server/src/main/resources/application.properties
@@ -1,12 +1,15 @@
+
 spring.datasource.tomcat.max-wait=20000
 spring.datasource.tomcat.remove-abandoned-timeout=360000
 spring.datasource.tomcat.test-on-borrow=true
-# ensure RDS reconnect behavior (issue #53)
+# ensure RDS reconnect
+behavior (issue #53)
 spring.datasource.tomcat.connectionProperties=socketTimeout=20;connectTimeout=10;loginTimeout=10;
 grpc.server.port=9443
 grpc.server.security.enabled=true
 grpc.server.security.certificateChain=localhost.crt
 grpc.server.security.privateKey=localhost.key
 
-# no factcast-accesss.json is provided
+# no factcast-accesss.json
+is provided
 factcast.security.enabled=false
```

2021-09-03 09:38 UTC, merged

2021-09-06 07:41 UTC, BernhardBln commented on pom.xml
> +								<include>**/*.xsd</include>
Hm, while IntelliJ kind of aligns the =, the spotless formatter would mainly remove leading and trailing spaces.